### Text Preprocessing

In [1]:
import numpy as np
import tensorflow 
from tensorflow import keras
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN

In [2]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
tokenizer = Tokenizer(oov_token="<nothing>")
tokenizer.fit_on_texts(docs)

In [4]:
tokenizer.word_index

{'<nothing>': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [5]:
tokenizer.document_count

10

In [6]:
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[10, 2],
 [2, 2],
 [4, 4, 11],
 [3, 12, 3, 2, 3],
 [13, 14, 5, 6],
 [7, 7],
 [8, 8],
 [9, 9],
 [15, 16, 5, 6],
 [17, 18]]

In [8]:
sequences = pad_sequences(sequences, padding="post")
sequences

array([[10,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 4,  4, 11,  0,  0],
       [ 3, 12,  3,  2,  3],
       [13, 14,  5,  6,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [15, 16,  5,  6,  0],
       [17, 18,  0,  0,  0]], dtype=int32)

### Sentiment Analysis - (Integer Encoding)

In [9]:
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [10]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [11]:
X_train.shape

(25000,)

In [12]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [13]:
X_train = pad_sequences(X_train, padding="post", maxlen=400)
X_test = pad_sequences(X_test, padding="post", maxlen=400)

In [14]:
X_train.shape

(25000, 400)

In [15]:
model = Sequential()

model.add(SimpleRNN(32, input_shape=(1000,1), return_sequences=False))
model.add(Dense(1, activation="sigmoid"))

model.summary()

C:\Users\bhushan.chitte\AppData\Roaming\Python\Python310\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [17]:
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 18ms/step - accuracy: 0.4990 - loss: 0.6950 - val_accuracy: 0.5044 - val_loss: 0.6934
Epoch 2/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - accuracy: 0.5008 - loss: 0.6942 - val_accuracy: 0.5051 - val_loss: 0.6934
Epoch 3/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 26s 33ms/step - accuracy: 0.5019 - loss: 0.6938 - val_accuracy: 0.5044 - val_loss: 0.6948
Epoch 4/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 17s 22ms/step - accuracy: 0.5009 - loss: 0.6943 - val_accuracy: 0.5024 - val_loss: 0.6960
Epoch 5/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 18ms/step - accuracy: 0.5075 - loss: 0.6942 - val_accuracy: 0.5003 - val_loss: 0.6940
Epoch 6/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 15s 19ms/step - accuracy: 0.5060 - loss: 0.6939 - val_accuracy: 0.4952 - val_loss: 0.6962
Epoch 7/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 22s 28ms/step - accuracy: 0.5028 - loss: 0.6946 - val_accuracy: 0.5017 - val_loss: 0.6938
Epoch 8/10
782/782 ━━━━━━━━━━━━━━━━━━━━ 16s 20ms/step - accuracy: 0.5012 - loss: 0.6940 - 

### Sentiment Analysis - (Embedding)

In [42]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [43]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(docs)

In [44]:
len(tokenizer.word_index)

17

In [45]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [46]:
sequences = pad_sequences(sequences, padding="post")
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [59]:
model = Sequential()

model.add(Embedding(17, output_dim=2, input_shape=(5,)))

model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 5, 2)           │            34 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 34 (136.00 B)

 Trainable params: 34 (136.00 B)

 Non-trainable params: 0 (0.00 B)

In [60]:
model.compile("adam", "accuracy")

In [61]:
sample_sequences = np.array([[1, 2, 3, 4, 0]], dtype=np.int32)  # shape (1,5)
predictions = model.predict(sample_sequences)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[[-0.01368726  0.04420226]
  [ 0.04856794  0.03722182]
  [-0.01488273 -0.03191884]
  [ 0.03036628 -0.01107427]
  [-0.01244498  0.00303024]]]


### IMDB Dataset

In [120]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=10000)

In [121]:
X_train = pad_sequences(X_train, maxlen=400, padding="post")
X_test = pad_sequences(X_test, maxlen=400, padding="post")

In [122]:
model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=32))
model.add(SimpleRNN(32))
model.add(Dense(1, activation="sigmoid"))

In [123]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [124]:
history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 18s 43ms/step - accuracy: 0.5022 - loss: 0.6929 - val_accuracy: 0.5080 - val_loss: 0.6911
Epoch 2/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 12s 30ms/step - accuracy: 0.5457 - loss: 0.6681 - val_accuracy: 0.5070 - val_loss: 0.6974
Epoch 3/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 14s 36ms/step - accuracy: 0.5650 - loss: 0.6310 - val_accuracy: 0.5093 - val_loss: 0.7114
Epoch 4/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 19s 31ms/step - accuracy: 0.5736 - loss: 0.6018 - val_accuracy: 0.5081 - val_loss: 0.7184
Epoch 5/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 22s 56ms/step - accuracy: 0.5769 - loss: 0.6015 - val_accuracy: 0.5056 - val_loss: 0.7266
Epoch 6/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 25s 63ms/step - accuracy: 0.5786 - loss: 0.5984 - val_accuracy: 0.5016 - val_loss: 0.7472
Epoch 7/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 24s 62ms/step - accuracy: 0.5811 - loss: 0.5904 - val_accuracy: 0.5050 - val_loss: 0.7575
Epoch 8/10
391/391 ━━━━━━━━━━━━━━━━━━━━ 41s 62ms/step - accuracy: 0.5870 - loss: 0.5866 - 

In [129]:
def predict_sentiment(text, model, tokenizer, max_len=400):
    """
    Predict sentiment of a given text using a trained SimpleRNN model.
    
    Args:
        text (str): Input sentence
        model: Trained Keras model
        tokenizer: Fitted tokenizer
        max_len (int): Max sequence length used during training
    
    Returns:
        dict: sentiment label and probability
    """
    
    # Convert text to sequence
    sequence = tokenizer.texts_to_sequences([text])
    
    # Pad sequence
    padded = pad_sequences(sequence, maxlen=max_len, padding='post', truncating='post')
    
    # Predict
    prediction = model.predict(padded)[0][0]
    
    # Convert to label
    if prediction >= 0.5:
        sentiment = "Positive"
    else:
        sentiment = "Negative"
    
    return {
        "text": text,
        "sentiment": sentiment,
        "confidence": float(prediction)
    }

In [130]:
text = "I really loved this movie!"
result = predict_sentiment(text, model, tokenizer)

print(result)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
{'text': 'I really loved this movie!', 'sentiment': 'Negative', 'confidence': 0.46021077036857605}
